/****************************************************************************** 
MCP4725 Example Waveform Sketch
Joel Bartlett
SparkFun Electronics
Sept. 11, 2014
https://github.com/sparkfun/MCP4725_Breakout

This sketch takes data from a lookup table to provide 
waveforms to be generated by the MCP4725 DAC. 

Development environment specifics:
Arduino 1.0+
Hardware Version V14

This code is beerware; if you see me (or any other SparkFun employee) at the local, 
and you've found our code helpful, please buy us a round!

Distributed as-is; no warranty is given. 

This code builds off the sketch written by Mark VandeWettering, which can be found here:
http://brainwagon.org/2011/02/24/arduino-mcp4725-breakout-board/
*/

#include <Wire.h>//Include the Wire library to talk I2C

//This is the I2C Address of the MCP4725, by default (A0 pulled to GND).
//Please note that this breakout is for the MCP4725A0. 
#define MCP4725_ADDR 0x60   
//For devices with A0 pulled HIGH, use 0x61

//Sinewave Tables were generated using this calculator:
//http://www.daycounter.com/Calculators/Sine-Generator-Calculator.phtml

int out = 4095;
int aOne = 0;
int aTwo = 0;

void setup()
{
  Serial.begin(9600);
  Wire.begin();
  pinMode(13, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(A0, INPUT);
  pinMode(A1, INPUT);
}
//---------------------------------------------------
void loop()
{
  digitalWrite(13, HIGH);
  digitalWrite(12, HIGH);
  Wire.beginTransmission(MCP4725_ADDR);
  Wire.write(64);                     // cmd to update the DAC
  Serial.print(out, BIN);
  Serial.print("\n");
  Wire.write(out >> 4);        // the 8 most significant bits...
  Serial.print(out >> 4, BIN);
  Serial.print("\n");
  Wire.write((out & 15) << 4); // the 4 least significant bits...
  Serial.print((out & 15) << 4, BIN);
  Serial.print("\n\n");
  aOne = analogRead(A0);
  Serial.print(aOne, DEC);
  Serial.print("\n");
  aTwo = analogRead(A1);
  Serial.print(aTwo, DEC);
  Serial.print("\n\n");
  Wire.endTransmission();
}
